config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  resources :events

  namespace :admin do
    root 'dashboard#index'
    resources :events
  end

  root 'welcome#index'

end

app/models/admin.rb
class Admin
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/models/event.rb
class Event
  include Mongoid::Document
  extend SimpleCalendar
  has_calendar :attribute => [:date_start, :date_end]

  field :date_start, type: Date
  field :date_end, type: Date
  field :name, type: String
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_filter :authorize_admin

  def index
  end


  private
  def authorize_admin
    unless admin_signed_in?
      redirect_to root_path, :flash => { :error => "Insufficient rights!" }
    end
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::DashboardController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to [:admin, @event], notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: [:admin, @event] }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to [:admin, @event], notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: [:admin, @event] }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to admin_events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:date_start, :date_end, :name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:date, :name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def semantic_previous_link
    ->(param, date_range) { link_to raw("&laquo;"), param => date_range.first - 1.day }
  end

  def semantic_next_link
    ->(param, date_range) { link_to raw("&raquo;"), param => date_range.last + 1.day }
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/dashboard/index.haml
%h1
  Admin panel
= link_to "Manage Events", admin_events_path, class: "ui blue button"

app/views/admin/events/_form.haml
= form_for([:admin,@event], :html => {:class => 'ui form'})  do |f|
  - if @event.errors.any?
    #error_explanation
      %h2
        = pluralize(@event.errors.count, "error")
        prohibited this event from being saved:
      %ul
        - @event.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :date_start
    %br/
    = f.text_field :date_start
  .field
    = f.label :date_end
    %br/
    = f.text_field :date_end
  .field
    = f.label :name
    %br/
    = f.text_field :name


  = f.submit class: "ui right attached blue button"

app/views/admin/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', admin_events_path %>

app/views/admin/events/index.haml
%p#notice= notice
%h1 Listing Events
%table.ui.table
  %thead
    %tr
      %th Start Date
      %th End Date
      %th Name
      %th{:colspan => "3"}
  %tbody
    - @events.each do |event|
      %tr
        %td= event.date_start
        %td= event.date_end
        %td= event.name
        %td= link_to 'Show', [:admin, event], class: "ui blue button"
        %td= link_to 'Edit', edit_admin_event_path(event), class: "ui yellow button"
        %td= link_to 'Remove', [:admin, event], method: :delete, data: { confirm: 'Are you sure?' }, class: "ui red button"
%br/
= link_to 'New Event', new_admin_event_path, class: "ui green button"

app/views/admin/events/new.haml
%h1 New Event
= render 'form'
= link_to 'Back', admin_events_path, class: "ui left attached red button"

app/views/admin/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start Date:</strong>
  <%= @event.date_start %>
</p>

<p>
  <strong>End Date:</strong>
  <%= @event.date_end %>
</p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<%= link_to 'Edit', edit_admin_event_path(@event) %> |
<%= link_to 'Back', admin_events_path %>

app/views/events/_form.haml
= form_for(@event, :html => {:class => 'ui form'})  do |f|
  - if @event.errors.any?
    #error_explanation
      %h2
        = pluralize(@event.errors.count, "error")
        prohibited this event from being saved:
      %ul
        - @event.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :date_start
    %br/
    = f.text_field :date_start
  .field
    = f.label :date_end
    %br/
    = f.text_field :date_end
  .field
    = f.label :name
    %br/
    = f.text_field :name


  = f.submit class: "ui right attached blue button"

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.haml
%p#notice= notice
%h1 Listing Events
= month_calendar previous_link: semantic_previous_link, next_link: semantic_next_link, table: {class: "ui calendar table"}, events: @events do |date, events|
  = date.mday
  %br
  - events.each do |event|
    = event.name
-# %table.ui.table
  %thead
    %tr
      %th Start Date
      %th End Date
      %th Name
      %th{:colspan => "3"}
  %tbody
    - @events.each do |event|
      %tr
        %td= event.date_start
        %td= event.date_end
        %td= event.name
%br/

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start Date:</strong>
  <%= @event.date_start %>
</p>

<p>
  <strong>End Date:</strong>
  <%= @event.date_end %>
</p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.haml
!!!
%html
  %head
    %title GregoryMuseum
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .ui.page.grid
      .row
        .column.padding-reset
          = render 'shared/navbar'
      .row
        .column.padding-reset
          = render 'shared/alerts'
          = yield
      .row
        .column.padding-reset
          = render 'shared/footer'

app/views/shared/_alerts.haml
- if flash[:notice]
  .sixteen.wide.column.ui.info.message
    %i.close.icon
    .header
      Notice
    %p
      =flash[:notice]
- if flash[:error]
  .sixteen.wide.column.ui.negative.message
    %i.close.icon
    .header
      Notice
    %p
      =flash[:error]
- if flash[:warning]
  .sixteen.wide.column.ui.yellow.message
    %i.close.icon
    .header
      Notice
    %p
      =flash[:warning]
- if flash[:alert]
  .sixteen.wide.column.ui.negative.message
    %i.close.icon
    .header
      Notice
    %p
      =flash[:alert]

app/views/shared/_footer.haml
%footer.page-footer.ui.sticky.inverted.vertical.segment
  .ui.stackable.center.aligned.page.grid
    .ten.wide.column
    .six.wide.column
      %h5.ui.inverted.header Contact Us
      %addr
        1895 Heitz Place Courthouse
        %p
          %br
          Phone: 516-822-7505
          %br
          Fax: 516-822-3227

app/views/shared/_navbar.haml
.row
  .ui.menu.navbar.inverted.attached
    %a.brand.item{:href => root_path } Gregory Museum
    %a.item{:href => root_path } About
    %a.item{:href => events_path } Events
    - if admin_signed_in?
      %a.item{:href => admin_root_path } Admin Panel
    .right.menu
      - if admin_signed_in?
        .ui.simple.dropdown.item
          = current_admin.email
          %i.dropdown.icon
          .menu
            .item
              =link_to "Edit account", edit_admin_registration_path, style: "color:black"
            .ui.divider
            .item
              =link_to('Logout', destroy_admin_session_path, :method => :delete, style: "color:black")

app/views/welcome/index.haml
.ui.green.inverted.vertical.segment
  .ui.very.relaxed.stackable.page.grid
    .row
      .column
        %h1.center.aligned.ui.inverted.header
          The Hicksville Gregory Museum
    .row
      .sixteen.wide.column
        %h3.ui.inverted.header Long Island Earth Science Center
        %p The Hicksville Gregory Museum has a rich history, and provides opportunity to learn about Earth Science.
        %p We have activities prepared for all ages, and support group work for school field trips.
        %p Additionally we have great volunteering opportunities for students.
        .ui.basic.inverted.animated.button
          .visible.content Learn More
          .hidden.content
            %i.right.arrow.icon
.ui.vertical.feature.segment
  .ui.centered.page.grid
    .fourteen.wide.column
      .ui.three.column.center.aligned.stackable.divided.grid
        .column
          .ui.icon.header
            %i.university.icon
            History
          %p We actively maintain the outside of the museum to preserve the Victorian appearance.
          %p Our museum contains a large assortment of interesting minerals, fossils, and more.
        .column
          .ui.icon.header
            %i.book.icon
            Learning
          %p We are a small museum dedicated to teaching visitors about the sciences.
          %p The small size allows us to provide you with a better learning opportunity, much the same way smaller class sizes in schools work.
        .column
          .ui.icon.header
            %i.leaf.icon
            Variety
          %p Our artifacts are spread out, providing you with a view of various minerals, fossils, butterflies.
          %p Additionally, we have the largest mineral collection on Long Island.

          %br